### ISSUE TITLE
”Param“, “power" and "SOP"

### ISSUE THREAD

**Issue by 2ephyrus** [BICLab/Spike-Driven-Transformer-V2#10]
How is "Param" calculated in the experimental table? Can you provide the calculation method or code?

**Comment by jkhu29** [comment]
- Param: Please refer to [this line](https://github.com/BICLab/Spike-Driven-Transformer-V2/blob/main/classification/main_finetune.py#L425).
- Power: Please refer to [Spike-driven Transformer](https://openreview.net/forum?id=9FmolyOHi5).
- SOP: No "SOP" in our paper.
