### ISSUE TITLE
重参数化输入

### ISSUE THREAD

**Issue by 2ephyrus** [BICLab/Spike-Driven-Transformer-V2#12]
抱歉，在DBB中我没有找到关于重参数化输入的部分。能否简单谈谈，堆叠卷积层间的输入是如何重参数化为第一层输入形式的？十分期待您的回复

**Comment by jkhu29** [comment]
Please refer to [this issue](https://github.com/BICLab/Spike-Driven-Transformer-V2/issues/4).
