### ISSUE TITLE
what is models_sew in your code

### ISSUE THREAD

**Issue by Kiwiwiki** [BICLab/Spike-Driven-Transformer-V2#2]
Congrats on your new work!!
I tried to reproduce your work, but cannot find the definition of models_sew module as in the file main_finetune.py.  could be anything missing in uploaded codes?

**Comment by jkhu29** [comment]
We will submit the relevant code within two weeks, btw, `model_sew` is only the code related to the ablation studies, you can comment as you like.

**Comment by goutianrui** [comment]
您好~已经过去两周啦，请问您models_sew.py文件可以上传到仓库了嘛

**Comment by liusimin-88** [comment]
请问上传了么？models_sew模块文件，没找到呢

**Comment by VVcrash** [comment]
hallo, about models_sew
