### ISSUE TITLE
Request for the checkpoints

### ISSUE THREAD

**Issue by mi804** [BICLab/Spike-Driven-Transformer-V2#5]
Great thanks for your work! Could you please share the checkpoints of Meta-SpikeFormer models  on ImageNet?

**Comment by ldkong1205** [comment]
Hi @mi804, @jkhu29, @YifanXu74, @BICLab, thanks for sharing your work! Any update for the release of model checkpoints?

**Comment by jkhu29** [comment]
Please feel free to download the ckpt and the training log of 55M-kd of Spike-Driven-Transformer V2 from [this link](https://drive.google.com/drive/folders/12JcIRG8BF6JcgPsXIetSS14udtHXeSSx?usp=sharing).
